---
title: the collection
first: T
copy: he stereo photos you see in Looking Glass VR are sele ed excerpts from the Keystone View Company’s ‘Tour of the World’, a tiny glimpse of Keystone’s internationally themed stereo photography colle ion. From 1892 to 1933, over 300,000 such cards were produced. However, in 1978, the company's records and inventory of negatives were eventually donated to the UCR/California Museum of Photography at the University of California Riverside, where they are now known as the Keystone-Mast colle ion.
