---
title: credits and thanks
first: A
copy: dditional hand lettering by Tobias Saul and illustration by Matt Weems. Lighting optimization by Boris Blosse. Prototyped with the help of Kevin Olson and Suzanne Leibrick. Sound effe s used from freesound.org. (A B C D E F G H) With Music from the Open Music Archive.
authors:
  title: Looking Glass VR was created by
  joeb: Joe Boyle
  kevinc: with 3D art by Kevin Castaneda
