---
title: how to use looking glass vr
instructions:
  - Make sure you have a Google Cardboard headset. (One with a trigger!) 
  - Install Looking Glass VR from the Google Play Store.
  - Turn on your WiFi & launch the application!
  - Click your trigger on the stereoscope to get started!
extra: If your Cardboard device does not have a trigger, you can use a bluetooth controller to interact with the application.
