---
first: W
copy: elcome to Looking Glass VR! Looking Glass VR is a mobile application for Google Cardboard which brings historic stereographic 3D photos from yesteryear into focus! You can find Looking Glass VR in the Google Play Store, but to get the 3D effe  you will need to have a Google Cardboard VR Device with a trigger.
