---

h1:
  font-family: octavian regular
  font-size: 22px

h2:
  font-family: serial regular
  font-size: 55px

copy1:
  font-family: independence regular
  font-size: 29px

copy2:
  font-family: Garamond
  font-size: 116px
