---
url: http://staging.lookingglass.com/
title: Looking Glass VR
description: Windows to the past are open at last
keywords: VR, VR app, looking glass
tracking_id: UA-89300822-1
share: images/share.jpg
repo: https://github.com/lookingglassvr/lookingglass
social:
  facebook: joesballs.com
  twitter: joesballs.com
